language: node_js
node_js:
  - "7"
  - "6"
branches:
  only: 
    - master
env:
  - BUILD_SCRIPT=.build-tsc.sh
  - BUILD_SCRIPT=.build-webpack.sh
  - BUILD_SCRIPT=.build-test.sh
script: chmod a+x $BUILD_SCRIPT && ./$BUILD_SCRIPT